---
title: "Fragebogen"
output: html_document
---
| Fragen                                                                                                                                                                         | Antworten                                                                                                                                              |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|
| Ich   fahre:                                                                                                                                                                   | Fahrrad   <br>   Lastenfahrrad                                                                                                                             |
| Wofür   nutzt du das Lastenfahrrad hauptsächlich?                                                                                                                              | Transport von Kindern   <br>   privater Transport von Einkäufen / Gegenständen / Haustieren    <br>  gewerbliche Nutzung  (z.B.   Lieferdienst)    <br>  Sonstiges |
| Was für   ein Lastenrad nutzt du hauptsächlich?                                                                                                                                | Post bike (einspurig)  <br>    Longtail (einspurig)    <br>  Frontloader (einspurig)    <br>  Frontloader (mehrspurig)   <br>   Schwerlast (mehrspurig)    <br>  Anhänger  |
| In   welcher Stadt fährst du hauptsächlich (Lasten-)Fahrrad?                                                                                                                   |                                                                                                                                                        |
| Nutzt du   das (Lasten-)Fahrrad regelmäßig in deinem Alltag oder unregelmäßig für   einzelne Gelegenheiten?                                                                    | 1 sehr unregelmäßig    <br> bis <br>  6 sehr regelmäßig                                                                                                             |
| Wie   häufig fährst du dir bisher unbekannte Routen mit dem (Lasten-)Fahrrad?                                                                                                  | 1 sehr selten    <br> bis <br>  6 sehr häufig                                                                                                                       |
| Hat dein   (Lasten-)Fahrrad einen Elektro-Antrieb?                                                                                                                             | Ja   <br>   Nein                                                                                                                                           |
| Wie   zufrieden bist du insgesamt mit der Fahrradinfrastruktur in dem Gebiet, in   dem du alltäglich fährst?                                                                   | 1 sehr unzufrieden   <br> über <br>  3 weder noch   <br> bis <br>  5 sehr zufrieden                                                                                             |
| Welches   Routing verwendest du hauptsächlich zum (Lasten-)Fahrradfahren?                                                                                                      | Google Maps   <br>   OpenStreetMap   <br>   Bike Citizens  <br>    CityMapper   <br>   Komoot   <br>   ich nutze kein Routing  <br>    Sonstiges                               |
| Wie   zufrieden bist du mit dem Routing?                                                                                                                                       | 1 sehr unzufrieden   <br> über <br>  3 weder noch   <br> bis <br>  5 sehr zufrieden                                                                                              |
| **Im   folgenden zeigen wir dir verschiedene Hindernisse. Wie viele Minuten zur Umfahrung des Hindernisses würdest du auf deinen alltäglichen   Routen maximal in Kauf nehmen?** |                                                                                                                                                        |
| nicht /   kaum passierbarer Stau durch Autoverkehr                                                                                                                             | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| schmale   Radwege (< 1,5 m)                                                                                                                                                     | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Kopfsteinplaster                                                                                                                                                                | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| unebener   Straßenbelag (z.B. durch Wurzeln und Schlaglöcher)                                                                                                                   | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Bordsteine                                                                                                                                                                      | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Poller   / Drängelgitter                                                                                                                                                        | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Fußverkehr   (z.B. geteilter Fuß- und Radweg)                                                                                                                                   | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Baustellen   auf der Fahrbahn                                                                                                                                                   | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Steigung                                                                                                                                                                        | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Gefährliche   Kreuzungen                                                                                                                                                        | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Hauptstraßen   ohne Schutzstreifen (dichtes, schnelles Überholen / Drängeln)                                                                                                    | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| schlecht   passierbarer Gegenverkehr (z.B. Einbahnstraßen frei für Fahrräder)                                                                                                   | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| Fußgängerzone:   Radfahrende müssen absteigen                                                                                                                                   | 0 min   <br>   2 min    <br>  4 min     <br> 6 min    <br>  8 min   <br>   10 min oder mehr                                                                                |
| **Wie häufig kommen diese Hindernisse in den Gebiet vor, in dem du alltäglich (Lasten-)Fahrrad fährst?**                                                                         |                                                                                                                                                        |
| nicht /   kaum passierbarer Stau durch Autoverkehr                                                                                                                             | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| schmale   Radwege (< 1,5 m)                                                                                                                                                    | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Kopfsteinplaster                                                                                                                                                                 | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| unebener   Straßenbelag (z.B. durch Wurzeln und Schlaglöcher)                                                                                                                    | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Bordsteine                                                                                                                                                                      | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Poller /   Drängelgitter                                                                                                                                                         | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Fußverkehr   (z.B. geteilter Fuß- und Radweg)                                                                                                                                    | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Baustellen   auf der Fahrbahn                                                                                                                                                    | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Steigung                                                                                                                                                                         | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| gefährliche   Kreuzungen                                                                                                                                                         | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Hauptstraßen   ohne Schutzstreifen (dichtes, schnelles Überholen / Drängeln)                                                                                                     | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| schlecht   passierbarer Gegenverkehr (z.B. Einbahnstraßen frei für Fahrräder)                                                                                                    | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Fußgängerzone:   Radfahrende müssen absteigen                                                                                                                                    | 1 sehr selten  <br> über <br>    3 manchmal  <br> bis <br>    5 sehr häufig                                                                                                       |
| Gibt es   sonstige Probleme oder Hindernisse beim (Lasten-)Radfahren, die hier nicht   berücksichtigt wurden?                                                                  |                                                                                                                                                        |
| Dein   Geschlecht                                                                                                                                                              | keine Angabe  <br>    weiblich    <br>  männlich  <br>    nicht-binär                                                                                              |
| Dein   Alter                                                                                                                                                                   |                                                                                                                                                        |
| Möchtest   du dich als Beta-Tester\*in für unser Lastenrad-Routing eintragen?                                                                                                  | Ja    <br>  Nein                                                                                                                                           |